# 16 OpenTripMap Expanded Collection

Collect a broader tourism-focused OpenTripMap POI set for Istanbul using manual landmark-center coordinates.

In [41]:
import os
import time
import requests
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 160)

In [42]:
LANG = "en"
COUNTRY = "TR"
RADIUS_METERS = 1400
LIMIT_PER_AREA = 40
DETAIL_LIMIT = 20
KIND_FILTER = "museums,historic_architecture,monuments,architecture,churches,mosques,interesting_places"

OUTPUT_PREFIX = "../data/processed/opentripmap_expanded"

TARGET_CENTERS = [
    {"query_name": "Sultanahmet Core", "lat": 41.0054, "lon": 28.9768},
    {"query_name": "Hagia Sophia / Basilica Cistern", "lat": 41.0080, "lon": 28.9799},
    {"query_name": "Topkapi Palace", "lat": 41.0115, "lon": 28.9833},
    {"query_name": "Eminonu / Spice Bazaar", "lat": 41.0165, "lon": 28.9702},
    {"query_name": "Suleymaniye", "lat": 41.0162, "lon": 28.9638},
    {"query_name": "Fatih / Valens Aqueduct", "lat": 41.0170, "lon": 28.9565},
    {"query_name": "Galata Tower", "lat": 41.0257, "lon": 28.9744},
    {"query_name": "Istiklal / Pera", "lat": 41.0339, "lon": 28.9779},
    {"query_name": "Dolmabahce", "lat": 41.0392, "lon": 29.0007},
    {"query_name": "Ortakoy", "lat": 41.0473, "lon": 29.0260},
    {"query_name": "Uskudar Waterfront", "lat": 41.0258, "lon": 29.0152},
    {"query_name": "Maiden's Tower Coast", "lat": 41.0211, "lon": 29.0041},
    {"query_name": "Kadikoy Historic Center", "lat": 40.9909, "lon": 29.0263},
    {"query_name": "Balat / Fener", "lat": 41.0297, "lon": 28.9497},
    {"query_name": "Beylerbeyi Palace", "lat": 41.0420, "lon": 29.0405},
    {"query_name": "Rumeli Hisari", "lat": 41.0849, "lon": 29.0568},
    {"query_name": "Eyup / Pierre Loti", "lat": 41.0480, "lon": 28.9327},
    {"query_name": "Yildiz Palace", "lat": 41.0438, "lon": 29.0125},
]

OPENTRIPMAP_API_KEY = os.getenv("OPENTRIPMAP_API_KEY")
if not OPENTRIPMAP_API_KEY:
    OPENTRIPMAP_API_KEY = input("Paste OpenTripMap API key: ").strip()

print("Key loaded:", bool(OPENTRIPMAP_API_KEY))
print("Target centers:", len(TARGET_CENTERS))

Key loaded: True
Target centers: 18

## Helpers

In [43]:
BASE_URL = f"https://api.opentripmap.com/0.1/{LANG}/places"


def otm_get(method, params=None):
    if not OPENTRIPMAP_API_KEY:
        raise ValueError("OPENTRIPMAP_API_KEY is missing")

    query = dict(params or {})
    query["apikey"] = OPENTRIPMAP_API_KEY

    url = f"{BASE_URL}/{method}"
    response = requests.get(url, params=query, timeout=20)

    if response.status_code != 200:
        debug = {
            "status_code": response.status_code,
            "response_text": response.text[:500],
            "url": response.url,
        }
        print("OpenTripMap error debug:", debug)
        response.raise_for_status()

    return response.json()


def get_places_radius(lat, lon, radius=1000, limit=20, kinds=None, rate=2, fmt="json"):
    params = {
        "radius": radius,
        "lon": lon,
        "lat": lat,
        "limit": limit,
        "rate": rate,
        "format": fmt,
    }
    if kinds:
        params["kinds"] = kinds
    return otm_get("radius", params)


def get_place_details(xid):
    return otm_get(f"xid/{xid}")

## Step 1 - Collection centers

In [44]:
centers_df = pd.DataFrame(TARGET_CENTERS)
centers_df

                         query_name      lat      lon
0                  Sultanahmet Core  41.0054  28.9768
1   Hagia Sophia / Basilica Cistern  41.0080  28.9799
2                    Topkapi Palace  41.0115  28.9833
3            Eminonu / Spice Bazaar  41.0165  28.9702
4                       Suleymaniye  41.0162  28.9638
5           Fatih / Valens Aqueduct  41.0170  28.9565
6                      Galata Tower  41.0257  28.9744
7                   Istiklal / Pera  41.0339  28.9779
8                        Dolmabahce  41.0392  29.0007
9                           Ortakoy  41.0473  29.0260
10               Uskudar Waterfront  41.0258  29.0152
11             Maiden's Tower Coast  41.0211  29.0041
12          Kadikoy Historic Center  40.9909  29.0263
13                    Balat / Fener  41.0297  28.9497
14                Beylerbeyi Palace  41.0420  29.0405
15                    Rumeli Hisari  41.0849  29.0568
16               Eyup / Pierre Loti  41.0480  28.9327
17                    Yildiz Palace  41.0438  29.0125

## Step 2 - Pull nearby POIs

In [45]:
radius_frames = []

for _, center_row in centers_df.iterrows():
    radius_results = get_places_radius(
        lat=center_row["lat"],
        lon=center_row["lon"],
        radius=RADIUS_METERS,
        limit=LIMIT_PER_AREA,
        kinds=KIND_FILTER,
    )

    area_df = pd.DataFrame(radius_results)
    if not area_df.empty:
        area_df["query_area"] = center_row["query_name"]
        radius_frames.append(area_df)
    time.sleep(0.5)

radius_df = pd.concat(radius_frames, ignore_index=True) if radius_frames else pd.DataFrame()
if not radius_df.empty and "xid" in radius_df.columns:
    radius_df = radius_df.sort_values(["rate", "dist"], ascending=[False, True])
    radius_df = radius_df.drop_duplicates(subset=["xid"]).reset_index(drop=True)

radius_df.head(30)

,xid,name,dist,rate,osm,wikidata,kinds,point,query_area
0,N7215645385,The Blue Mosque,18.136162,7,node/7215645385,Q80541,"religion,mosques,interesting_places","{'lon': 28.976892471313477, 'lat': 41.00525283...",Sultanahmet Core
1,R1564032,Süleymaniye Mosque,18.644092,7,relation/1564032,Q178643,"religion,mosques,interesting_places","{'lon': 28.963977813720703, 'lat': 41.01630020...",Suleymaniye
2,Q5773394,Historic Areas of Istanbul,52.256390,7,NaN,Q5773394,"interesting_places,natural,nature_reserves,oth...","{'lon': 28.979930877685547, 'lat': 41.00846862...",Hagia Sophia / Basilica Cistern
3,R1555271,Hagia Sophia Grand Mosque,57.237152,7,relation/1555271,Q12506,"religion,mosques,churches,cultural,museums,int...","{'lon': 28.980009078979492, 'lat': 41.00850677...",Hagia Sophia / Basilica Cistern
4,W109862851,The Hagia Sophia Grand Mosque,57.237152,7,way/109862851,Q12506,"religion,mosques,churches,cultural,museums,int...","{'lon': 28.980009078979492, 'lat': 41.00850677...",Hagia Sophia / Basilica Cistern
5,Q2656937,Runic inscriptions in Hagia Sophia,102.822256,7,NaN,Q2656937,"other,unclassified_objects,interesting_places,...","{'lon': 28.97909927368164, 'lat': 41.008701324...",Hagia Sophia / Basilica Cistern
6,N415157636,Serpent Column,145.719100,7,node/415157636,Q588892,"historic,monuments_and_memorials,burial_places...","{'lon': 28.9751033782959, 'lat': 41.0056610107...",Sultanahmet Core
7,W103953125,Tomb of Sultan Ahmet,155.641087,7,way/103953125,Q80541,"religion,mosques,interesting_places","{'lon': 28.97703742980957, 'lat': 41.006790161...",Sultanahmet Core
8,W326372295,Yıldız Palace,700.923972,7,way/326372295,Q911734,"palaces,architecture,historic_architecture,cul...","{'lon': 29.01161766052246, 'lat': 41.050075531...",Yildiz Palace
9,N4477143891,Yıldız Palace,770.380137,7,node/4477143891,Q911734,"palaces,architecture,historic_architecture,int...","{'lon': 29.011703491210938, 'lat': 41.05071258...",Yildiz Palace
10,N7294561685,Chora Mosque,905.679630,7,node/7294561685,Q849489,"religion,mosques,churches,cultural,museums,int...","{'lon': 28.939090728759766, 'lat': 41.03109741...",Balat / Fener
11,W32395058,Kariye Museum,912.683339,7,way/32395058,Q849489,"religion,mosques,churches,cultural,museums,int...","{'lon': 28.939029693603516, 'lat': 41.03120040...",Balat / Fener
12,R7318154,Rumeli Fortress,8.978326,3,relation/7318154,Q90801,"fortifications,historic,cultural,museums,inter...","{'lon': 29.056764602661133, 'lat': 41.08497619...",Rumeli Hisari
13,W102190099,Osman ağa Mosque,16.349998,3,way/102190099,Q6029146,"religion,mosques,interesting_places","{'lon': 29.026123046875, 'lat': 40.99084091186...",Kadikoy Historic Center
14,W23236783,Galata Tower,17.032431,3,way/23236783,Q91274,"architecture,towers,interesting_places,observa...","{'lon': 28.974212646484375, 'lat': 41.02564239...",Galata Tower
15,N6919989286,Ortaköy Mosque,32.974679,3,node/6919989286,Q176380,"religion,mosques,interesting_places","{'lon': 29.02560806274414, 'lat': 41.047290802...",Ortakoy
16,Q105840441,Mısırlı Osman Ağa Fountain,41.479630,3,NaN,Q105840441,"fountains,historic,cultural,urban_environment,...","{'lon': 29.026735305786133, 'lat': 40.99107360...",Kadikoy Historic Center
17,N4519290891,Selman aga Camii,51.282068,3,node/4519290891,Q6056669,"religion,mosques,interesting_places","{'lon': 29.01579475402832, 'lat': 41.025699615...",Uskudar Waterfront
18,W261825033,Church of St. Mary of the Mongols,57.655526,3,way/261825033,Q1950180,"religion,churches,interesting_places,eastern_o...","{'lon': 28.949026107788086, 'lat': 41.02960205...",Balat / Fener
19,N269370709,Rumelihisarı,58.471295,3,node/269370709,Q90801,"fortifications,historic,interesting_places,cas...","{'lon': 29.056476593017578, 'lat': 41.08443450...",Rumeli Hisari
20,Q3082387,Church of the Virgin of the Pharos,59.812504,3,NaN,Q3082387,"religion,churches,interesting_places,other_chu...","{'lon': 28.977222442626953, 'lat': 41.00583267...",Sultanahmet Core
21,W498861735,Ortaköy Mosque,69.513470,3,way/498861735,Q176380,"religion,mosques,interesting_places","{'lon': 29.026826858520508, 'lat': 41.04729461...",Ortakoy
22,W600269984,Eyüp Sultan Mosque,80.304871,3,way/600269984,Q956677,"religion,mosques,interesting_places","{'lon': 28.93349838256836, 'lat': 41.047603607...",Eyup / Pierre Loti
23,W261821356,Eyüp Sultan Mosque,86.500391,3,way/261821356,Q956677,"religion,mosques,interesting_places","{'lon': 28.93372917175293, 'lat': 41.048011779...",Eyup / Pierre Loti
24,W61736367,Beylerbeyi Palace,87.157352,3,way/61736367,Q794349,"palaces,architecture,historic_architecture,cul...","{'lon': 29.040014266967773, 'lat': 41.04269409...",Beylerbeyi Palace
25,N4591192493,Spice Bazaar,92.140158,3,node/4591192493,Q668641,"view_points,other,interesting_places,shops,mar...","{'lon': 28.971256256103516, 'lat': 41.01628112...",Eminonu / Spice Bazaar
26,N3386270532,Galatasaray Museum,93.163832,3,node/3386270532,Q3329724,"cultural,museums,interesting_places,art_galleries","{'lon': 28.976940155029297, 'lat': 41.03348159...",Istiklal / Pera
27,W24826707,Dolmabahçe Palace,101.151027,3,way/24826707,Q274141,"gardens_and_parks,cultural,urban_environment,i...","{'lon': 28.99953842163086, 'lat': 41.038963317...",Dolmabahce
28,W175516451,Dolmabahce Palace,109.129014,3,way/175516451,Q274141,"palaces,architecture,historic_architecture,cul...","{'lon': 28.999526977539062, 'lat': 41.03878021...",Dolmabahce
29,Q16947921,Fountain of Ahmed III (Üsküdar),110.383145,3,NaN,Q16947921,"fountains,historic,cultural,urban_environment,...","{'lon': 29.01535415649414, 'lat': 41.026786804...",Uskudar Waterfront

In [46]:
if not radius_df.empty:
    display_cols = [c for c in ["query_area", "xid", "name", "kinds", "dist", "rate", "osm", "wikidata"] if c in radius_df.columns]
    print("Radius result shape:", radius_df.shape)
    print(radius_df[display_cols].head(40).to_string())
else:
    print("No radius results returned.")

Radius result shape: (395, 9)
                         query_area          xid                                name                                                                                                                                  kinds        dist  rate               osm    wikidata
0                  Sultanahmet Core  N7215645385                     The Blue Mosque                                                                                                    religion,mosques,interesting_places   18.136162     7   node/7215645385      Q80541
1                       Suleymaniye     R1564032                  Süleymaniye Mosque                                                                                                    religion,mosques,interesting_places   18.644092     7  relation/1564032     Q178643
2   Hagia Sophia / Basilica Cistern     Q5773394          Historic Areas of Istanbul                                                             interesting_places,natural,nature_reserves,other_nature_conservation_areas   52.256390     7               NaN    Q5773394
3   Hagia Sophia / Basilica Cistern     R1555271           Hagia Sophia Grand Mosque                                          religion,mosques,churches,cultural,museums,interesting_places,other_museums,catholic_churches   57.237152     7  relation/1555271      Q12506
4   Hagia Sophia / Basilica Cistern   W109862851       The Hagia Sophia Grand Mosque                                          religion,mosques,churches,cultural,museums,interesting_places,other_museums,catholic_churches   57.237152     7     way/109862851      Q12506
5   Hagia Sophia / Basilica Cistern     Q2656937  Runic inscriptions in Hagia Sophia                                                                          other,unclassified_objects,interesting_places,historic_object  102.822256     7               NaN    Q2656937
6                  Sultanahmet Core   N415157636                      Serpent Column  historic,monuments_and_memorials,burial_places,urban_environment,cultural,interesting_places,other_burial_places,sculptures,monuments  145.719100     7    node/415157636     Q588892
7                  Sultanahmet Core   W103953125                Tomb of Sultan Ahmet                                                                                                    religion,mosques,interesting_places  155.641087     7     way/103953125      Q80541
8                     Yildiz Palace   W326372295                       Yıldız Palace                                           palaces,architecture,historic_architecture,cultural,museums,interesting_places,other_museums  700.923972     7     way/326372295     Q911734
9                     Yildiz Palace  N4477143891                       Yıldız Palace                                                                          palaces,architecture,historic_architecture,interesting_places  770.380137     7   node/4477143891     Q911734
10                    Balat / Fener  N7294561685                        Chora Mosque                                             religion,mosques,churches,cultural,museums,interesting_places,other_museums,other_churches  905.679630     7   node/7294561685     Q849489
11                    Balat / Fener    W32395058                       Kariye Museum                                             religion,mosques,churches,cultural,museums,interesting_places,other_museums,other_churches  912.683339     7      way/32395058     Q849489
12                    Rumeli Hisari     R7318154                     Rumeli Fortress                                                    fortifications,historic,cultural,museums,interesting_places,castles,history_museums    8.978326     3  relation/7318154      Q90801
13          Kadikoy Historic Center   W102190099                    Osman ağa Mosque                                                                                                    religion,mosques,interesting_places   16.349998     3     way/102190099    Q6029146
14                     Galata Tower    W23236783                        Galata Tower                                                                              architecture,towers,interesting_places,observation_towers   17.032431     3      way/23236783      Q91274
15                          Ortakoy  N6919989286                      Ortaköy Mosque                                                                                                    religion,mosques,interesting_places   32.974679     3   node/6919989286     Q176380
16          Kadikoy Historic Center   Q105840441          Mısırlı Osman Ağa Fountain                          fountains,historic,cultural,urban_environment,monuments_and_memorials,interesting_places,sculptures,monuments   41.479630     3               NaN  Q105840441
17               Uskudar Waterfront  N4519290891                    Selman aga Camii                                                                                                    religion,mosques,interesting_places   51.282068     3   node/4519290891    Q6056669
18                    Balat / Fener   W261825033   Church of St. Mary of the Mongols                                                                         religion,churches,interesting_places,eastern_orthodox_churches   57.655526     3     way/261825033    Q1950180
19                    Rumeli Hisari   N269370709                        Rumelihisarı                                                                                     fortifications,historic,interesting_places,castles   58.471295     3    node/269370709      Q90801
20                 Sultanahmet Core     Q3082387  Church of the Virgin of the Pharos                                                                                    religion,churches,interesting_places,other_churches   59.812504     3               NaN    Q3082387
21                          Ortakoy   W498861735                      Ortaköy Mosque                                                                                                    religion,mosques,interesting_places   69.513470     3     way/498861735     Q176380
22               Eyup / Pierre Loti   W600269984                  Eyüp Sultan Mosque                                                                                                    religion,mosques,interesting_places   80.304871     3     way/600269984     Q956677
23               Eyup / Pierre Loti   W261821356                  Eyüp Sultan Mosque                                                                                                    religion,mosques,interesting_places   86.500391     3     way/261821356     Q956677
24                Beylerbeyi Palace    W61736367                   Beylerbeyi Palace                                           palaces,architecture,historic_architecture,cultural,museums,interesting_places,other_museums   87.157352     3      way/61736367     Q794349
25           Eminonu / Spice Bazaar  N4591192493                        Spice Bazaar                                                             view_points,other,interesting_places,shops,marketplaces,tourist_facilities   92.140158     3   node/4591192493     Q668641
26                  Istiklal / Pera  N3386270532                  Galatasaray Museum                                                                                      cultural,museums,interesting_places,art_galleries   93.163832     3   node/3386270532    Q3329724
27                       Dolmabahce    W24826707                   Dolmabahçe Palace                                                                        gardens_and_parks,cultural,urban_environment,interesting_places  101.151027     3      way/24826707     Q274141
28                       Dolmabahce   W175516451                   Dolmabahce Palace                                           palaces,architecture,historic_architecture,cultural,museums,interesting_places,other_museums  109.129014     3     way/175516451     Q274141
29               Uskudar Waterfront    Q16947921     Fountain of Ahmed III (Üsküdar)                          fountains,historic,cultural,urban_environment,monuments_and_memorials,interesting_places,sculptures,monuments  110.383145     3               NaN   Q16947921
30                Beylerbeyi Palace  N1964555485                   Beylerbeyi Palace                                                                          palaces,architecture,historic_architecture,interesting_places  111.083066     3   node/1964555485     Q794349
31                       Dolmabahce   W263949137                   Dolmabahçe Palace                                           palaces,architecture,historic_architecture,cultural,museums,interesting_places,other_museums  111.663130     3     way/263949137     Q274141
32               Uskudar Waterfront     R7321116                    Yeni Valide Cami                                                                                                    religion,mosques,interesting_places  112.003002     3  relation/7321116    Q2334567
33                          Ortakoy    Q59238241                  Ayios Fokas Church                                                                                              religion,other_temples,interesting_places  115.098597     3               NaN   Q59238241
34  Hagia Sophia / Basilica Cistern    W32396432           Sultan Ahmed III Fountain                                                                                fountains,cultural,urban_environment,interesting_places  118.099997     3      way/32396432    Q3076126
35           Eminonu / Spice Bazaar   W822870615                   New Mosque Square                                                                                                    religion,mosques,interesting_places  118.222346     3     way/822870615     Q911720
36               Uskudar Waterfront   W333931123               Mihrimah Sultan Camii                                                                                                    religion,mosques,interesting_places  126.948153     3     way/333931123    Q2537376
37               Uskudar Waterfront   W333931122               Mihrimah Sultan Camii                                                                                                    religion,mosques,interesting_places  130.279510     3     way/333931122    Q2537376
38               Uskudar Waterfront   W333931124               Mihrimah Sultan Camii                                                                                                    religion,mosques,interesting_places  130.614993     3     way/333931124    Q2537376
39                 Sultanahmet Core   N415157637               Obelisk of Theodosius                                    historic,monuments_and_memorials,urban_environment,cultural,interesting_places,sculptures,monuments  132.103709     3    node/415157637     Q763854

## Step 3 - Pull details for a controlled subset

In [47]:
detail_xids = radius_df["xid"].dropna().head(DETAIL_LIMIT).tolist() if "xid" in radius_df.columns else []
detail_xids

['N7215645385',
 'R1564032',
 'Q5773394',
 'R1555271',
 'W109862851',
 'Q2656937',
 'N415157636',
 'W103953125',
 'W326372295',
 'N4477143891',
 'N7294561685',
 'W32395058',
 'R7318154',
 'W102190099',
 'W23236783',
 'N6919989286',
 'Q105840441',
 'N4519290891',
 'W261825033',
 'N269370709']

In [48]:
detail_rows = []
area_lookup = radius_df[["xid", "query_area"]].drop_duplicates().set_index("xid")["query_area"].to_dict() if not radius_df.empty else {}

for xid in detail_xids:
    try:
        details = get_place_details(xid)
        details["query_area"] = area_lookup.get(xid)
        detail_rows.append(details)
        time.sleep(0.5)
    except Exception as exc:
        print(f"Skipping {xid}: {exc}")

details_df = pd.DataFrame(detail_rows)
details_df.head(20)

,xid,name,address,rate,osm,wikidata,kinds,url,sources,otm,wikipedia,image,preview,wikipedia_extracts,point,query_area,bbox
0,N7215645385,The Blue Mosque,"{'town': 'Fatih', 'house': 'Sultanahmet Camii'...",3h,node/7215645385,Q80541,"religion,mosques,interesting_places",https://www.geziyerler.com/sultan-ahmet-camii;...,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/N7215645385,https://en.wikipedia.org/wiki/Sultan%20Ahmed%2...,https://commons.wikimedia.org/wiki/File:Sultan...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Sultan Ahmed Mosque', 'text': 'S...","{'lon': 28.976892471313477, 'lat': 41.00525283...",Sultanahmet Core,NaN
1,R1564032,Süleymaniye Mosque,"{'city': 'Süleymaniye Mahallesi', 'road': 'Pro...",3h,relation/1564032,Q178643,"religion,mosques,interesting_places",https://www.geziyerler.com/suleymaniye-camii,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/R1564032,https://en.wikipedia.org/wiki/S%C3%BCleymaniye...,https://commons.wikimedia.org/wiki/File:Istanb...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Süleymaniye Mosque', 'text': 'Th...","{'lon': 28.963977813720703, 'lat': 41.01630020...",Suleymaniye,"{'lon_min': 28.963088, 'lon_max': 28.964576, '..."
2,Q5773394,Historic Areas of Istanbul,"{'city': 'Cankurtaran Mahallesi', 'town': 'Fat...",3h,NaN,Q5773394,"interesting_places,natural,nature_reserves,oth...",NaN,"{'geometry': 'wikidata', 'attributes': ['wikid...",https://opentripmap.com/en/card/Q5773394,https://en.wikipedia.org/wiki/Historic%20Areas...,https://commons.wikimedia.org/wiki/File:Istanb...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Historic Areas of Istanbul', 'te...","{'lon': 28.979930877685547, 'lat': 41.00846862...",Hagia Sophia / Basilica Cistern,NaN
3,R1555271,Hagia Sophia Grand Mosque,"{'city': 'Cankurtaran Mahallesi', 'road': 'Bab...",3h,relation/1555271,Q12506,"religion,mosques,churches,cultural,museums,int...",https://muze.gen.tr/muze-detay/ayasofya;https:...,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/R1555271,https://en.wikipedia.org/wiki/Hagia%20Sophia,https://commons.wikimedia.org/wiki/File:Hagia_...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Hagia Sophia', 'text': 'Hagia So...","{'lon': 28.980009078979492, 'lat': 41.00850677...",Hagia Sophia / Basilica Cistern,"{'lon_min': 28.978778, 'lon_max': 28.980948, '..."
4,W109862851,The Hagia Sophia Grand Mosque,"{'city': 'İstanbul', 'town': 'Fatih', 'state':...",3h,way/109862851,Q12506,"religion,mosques,churches,cultural,museums,int...",https://muze.gen.tr/muze-detay/ayasofya;https:...,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/W109862851,https://en.wikipedia.org/wiki/Hagia%20Sophia,https://commons.wikimedia.org/wiki/File:Hagia_...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Hagia Sophia', 'text': 'Hagia So...","{'lon': 28.980009078979492, 'lat': 41.00850677...",Hagia Sophia / Basilica Cistern,"{'lon_min': 28.979078, 'lon_max': 28.980917, '..."
5,Q2656937,Runic inscriptions in Hagia Sophia,"{'city': 'Cankurtaran Mahallesi', 'road': 'Caf...",3h,NaN,Q2656937,"other,unclassified_objects,interesting_places,...",NaN,"{'geometry': 'wikidata', 'attributes': ['wikid...",https://opentripmap.com/en/card/Q2656937,https://en.wikipedia.org/wiki/Runic%20inscript...,https://commons.wikimedia.org/wiki/File:Hagia-...,{'source': 'https://upload.wikimedia.org/wikip...,{'title': 'en:Runic inscriptions in Hagia Soph...,"{'lon': 28.97909927368164, 'lat': 41.008701324...",Hagia Sophia / Basilica Cistern,NaN
6,N415157636,Serpent Column,"{'city': 'Binbirdirek Mahallesi', 'town': 'Fat...",3h,node/415157636,Q588892,"historic,monuments_and_memorials,burial_places...",NaN,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/N415157636,https://en.wikipedia.org/wiki/Serpent%20Column,https://commons.wikimedia.org/wiki/File:Snake_...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Serpent Column', 'text': 'The Se...","{'lon': 28.9751033782959, 'lat': 41.0056610107...",Sultanahmet Core,NaN
7,W103953125,Tomb of Sultan Ahmet,"{'town': 'Fatih', 'state': 'Marmara Bölgesi', ...",3h,way/103953125,Q80541,"religion,mosques,interesting_places",http://www.bluemosque.co/,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/W103953125,https://en.wikipedia.org/wiki/Sultan%20Ahmed%2...,https://commons.wikimedia.org/wiki/File:Sultan...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Sultan Ahmed Mosque', 'text': 'S...","{'lon': 28.97703742980957, 'lat': 41.006790161...",Sultanahmet Core,"{'lon_min': 28.976633, 'lon_max': 28.977364, '..."
8,W326372295,Yıldız Palace,"{'city': 'Yıldız Mahallesi', 'road': 'Serenceb...",3h,way/326372295,Q911734,"palaces,architecture,historic_architecture,cul...",https://muze.gen.tr/,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/W326372295,https://en.wikipedia.org/wiki/Y%C4%B1ld%C4%B1z...,https://commons.wikimedia.org/wiki/File:%C4%B0...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Yıldız Palace', 'text': 'Yıldız ...","{'lon': 29.01161766052246, 'lat': 41.050075531...",Yildiz Palace,"{'lon_min': 29.01144, 'lon_max': 29.011737, 'l..."
9,N4477143891,Yıldız Palace,"{'city': 'Yıldız Mahallesi', 'town': 'Beşiktaş...",3h,node/4477143891,Q911734,"palaces,architecture,historic_architecture,int...",https://muze.gen.tr/,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/N4477143891,https://en.wikipedia.org/wiki/Y%C4%B1ld%C4%B1z...,https://commons.wikimedia.org/wiki/File:%C4%B0...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Yıldız Palace', 'text': 'Yıldız ...","{'lon': 29.011703491210938, 'lat': 41.05071258...",Yildiz Palace,NaN
10,N7294561685,Chora Mosque,"{'city': 'Derviş Ali Mahallesi', 'road': 'Kari...",3h,node/7294561685,Q849489,"religion,mosques,churches,cultural,museums,int...",https://muze.gen.tr/muze-detay/kariye,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/N7294561685,https://en.wikipedia.org/wiki/Chora%20Church,https://commons.wikimedia.org/wiki/File:Kariye...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Chora Church', 'text': 'The Kari...","{'lon': 28.939090728759766, 'lat': 41.03109741...",Balat / Fener,NaN
11,W32395058,Kariye Museum,"{'city': 'Derviş Ali Mahallesi', 'road': 'Kari...",3h,way/32395058,Q849489,"religion,mosques,churches,cultural,museums,int...",https://muze.gen.tr/muze-detay/kariye,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/W32395058,https://en.wikipedia.org/wiki/Chora%20Church,https://commons.wikimedia.org/wiki/File:Kariye...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Chora Church', 'text': 'The Kari...","{'lon': 28.939029693603516, 'lat': 41.03120040...",Balat / Fener,"{'lon_min': 28.938825, 'lon_max': 28.939213, '..."
12,R7318154,Rumeli Fortress,"{'road': 'Yahya Kemal Caddesi', 'town': 'Sarıy...",3,relation/7318154,Q90801,"fortifications,historic,cultural,museums,inter...",https://muze.gen.tr/muze-detay/rumeli;https://...,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/R7318154,https://en.wikipedia.org/wiki/Rumelihisar%C4%B1,https://commons.wikimedia.org/wiki/File:Twierd...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Rumelihisarı', 'text': 'Rumelihi...","{'lon': 29.056764602661133, 'lat': 41.08497619...",Rumeli Hisari,"{'lon_min': 29.055415, 'lon_max': 29.05688, 'l..."
13,W102190099,Osman ağa Mosque,"{'city': 'Osmanağa Mahallesi', 'town': 'Kadıkö...",3,way/102190099,Q6029146,"religion,mosques,interesting_places",NaN,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/W102190099,https://tr.wikipedia.org/wiki/Osmana%C4%9Fa%20...,https://commons.wikimedia.org/wiki/File:2021-0...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'tr:Osmanağa Camii', 'text': 'Osmana...","{'lon': 29.026123046875, 'lat': 40.99084091186...",Kadikoy Historic Center,"{'lon_min': 29.025956, 'lon_max': 29.02629, 'l..."
14,W23236783,Galata Tower,"{'city': 'Bereketzade Mahallesi', 'town': 'Bey...",3,way/23236783,Q91274,"architecture,towers,interesting_places,observa...",https://www.geziyerler.com/galata-kulesi;https...,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/W23236783,https://en.wikipedia.org/wiki/Galata%20Tower,https://commons.wikimedia.org/wiki/File:Galata...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Galata Tower', 'text': 'The Gala...","{'lon': 28.974212646484375, 'lat': 41.02564239...",Galata Tower,"{'lon_min': 28.97411, 'lon_max': 28.974316, 'l..."
15,N6919989286,Ortaköy Mosque,"{'city': 'Mecidiye Mahallesi', 'town': 'Beşikt...",3,node/6919989286,Q176380,"religion,mosques,interesting_places",NaN,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/N6919989286,https://en.wikipedia.org/wiki/Ortak%C3%B6y%20M...,https://commons.wikimedia.org/wiki/File:Istanb...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Ortaköy Mosque', 'text': 'Ortakö...","{'lon': 29.02560806274414, 'lat': 41.047290802...",Ortakoy,NaN
16,Q105840441,Mısırlı Osman Ağa Fountain,"{'city': 'Osmanağa Mahallesi', 'road': 'Söğütl...",3,NaN,Q105840441,"fountains,historic,cultural,urban_environment,...",NaN,"{'geometry': 'wikidata', 'attributes': ['wikid...",https://opentripmap.com/en/card/Q105840441,https://tr.wikipedia.org/wiki/M%C4%B1s%C4%B1rl...,https://commons.wikimedia.org/wiki/File:M%C4%B...,{'source': 'https://upload.wikimedia.org/wikip...,{'title': 'tr:Mısırlı Osman Ağa Çeşmesi (Kadık...,"{'lon': 29.026735305786133, 'lat': 40.99107360...",Kadikoy Historic Center,NaN
17,N4519290891,Selman aga Camii,"{'road': 'Selmani Pak Caddesi', 'town': 'Üsküd...",3,node/4519290891,Q6056669,"religion,mosques,interesting_places",NaN,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/N4519290891,https://tr.wikipedia.org/wiki/Selman%20A%C4%9F...,https://commons.wikimedia.org/wiki/File:%C3%9C...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'tr:Selman Ağa Camii', 'text': 'Selm...","{'lon': 29.01579475402832, 'lat': 41.025699615...",Uskudar Waterfront,NaN
18,W261825033,Church of St. Mary of the Mongols,"{'road': 'Tevki Cafer Mektebi Sokağı', 'town':...",3,way/261825033,Q1950180,"religion,churches,interesting_places,eastern_o...",NaN,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/W261825033,https://en.wikipedia.org/wiki/Church%20of%20Sa...,https://commons.wikimedia.org/wiki/File:StMary...,{'source': 'https://upload.wikimedia.org/wikip...,{'title': 'en:Church of Saint Mary of the Mong...,"{'lon': 28.949026107788086, 'lat': 41.02960205...",Balat / Fener,"{'lon_min': 28.948919, 'lon_max': 28.949169, '..."
19,N269370709,Rumelihisarı,"{'road': 'Yahya Kemal Caddesi', 'town': 'Sarıy...",3,node/269370709,Q90801,"fortifications,historic,interesting_places,cas...",https://muze.gen.tr/,"{'geometry': 'osm', 'attributes': ['osm', 'wik...",https://opentripmap.com/en/card/N269370709,https://en.wikipedia.org/wiki/Rumelihisar%C4%B1,https://commons.wikimedia.org/wiki/File:Twierd...,{'source': 'https://upload.wikimedia.org/wikip...,"{'title': 'en:Rumelihisarı', 'text': 'Rumelihi...","{'lon': 29.056476593017578, 'lat': 41.08443450...",Rumeli Hisari,NaN

## Save outputs

In [49]:
centers_df.to_csv(f"{OUTPUT_PREFIX}_centers.csv", index=False)
print(f"Saved: {OUTPUT_PREFIX}_centers.csv")

if radius_df.empty:
    print("Skipping save because no radius results were returned.")
else:
    radius_df.to_csv(f"{OUTPUT_PREFIX}_radius_results.csv", index=False)
    print(f"Saved: {OUTPUT_PREFIX}_radius_results.csv")

if 'details_df' in globals() and not details_df.empty:
    details_df.to_csv(f"{OUTPUT_PREFIX}_details_results.csv", index=False)
    print(f"Saved: {OUTPUT_PREFIX}_details_results.csv")
else:
    print("Skipping details save because no detail rows were collected.")

Saved: ../data/processed/opentripmap_expanded_centers.csv
Saved: ../data/processed/opentripmap_expanded_radius_results.csv
Saved: ../data/processed/opentripmap_expanded_details_results.csv

## Notes

- This expanded version uses manual tourism centers instead of area-name geocoding.
- Expanded outputs are written to `opentripmap_expanded_*` files so the smaller pilot outputs remain intact.
- If the expanded pull becomes too noisy, tighten `KIND_FILTER` or reduce `RADIUS_METERS`.
- If the expanded pull is still too small, increase `LIMIT_PER_AREA` before increasing `DETAIL_LIMIT`.